[package]
name = "sqlx-gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Generate Rust structs from database schema introspection"
readme = "../../README.md"

[[bin]]
name = "sqlx-gen"
required-features = ["cli"]

[features]
default = ["cli"]
cli = [
    "dep:sqlx",
    "dep:tokio",
    "dep:clap",
    "dep:heck",
    "dep:thiserror",
    "dep:quote",
    "dep:proc-macro2",
    "dep:syn",
    "dep:prettyplease",
    "dep:log",
    "dep:env_logger",
    "dep:tempfile",
]

[dependencies]
sqlx-gen-macros.workspace = true
sqlx = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
heck = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }
syn = { workspace = true, optional = true }
prettyplease = { workspace = true, optional = true }
log = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
