use std::path::Path;

use anyhow::Result;

use crate::codegen::GeneratedFile;

const HEADER: &str = "// Auto-generated by sqlx-gen. Do not edit.";

pub fn write_files(
    files: &[GeneratedFile],
    output_dir: &Path,
    single_file: bool,
    dry_run: bool,
) -> Result<()> {
    if dry_run {
        for f in files {
            println!("{}", build_file_content(f));
            println!();
        }
        return Ok(());
    }

    std::fs::create_dir_all(output_dir)?;

    if single_file {
        write_single_file(files, output_dir)?;
    } else {
        write_multi_files(files, output_dir)?;
    }

    Ok(())
}

fn build_file_content(f: &GeneratedFile) -> String {
    let mut content = String::new();
    content.push_str(HEADER);
    content.push('\n');
    if let Some(origin) = &f.origin {
        content.push_str(&format!("// {}\n", origin));
    }
    content.push('\n');
    content.push_str(&f.code);
    content
}

fn write_single_file(files: &[GeneratedFile], output_dir: &Path) -> Result<()> {
    let mut content = String::from(HEADER);
    content.push_str("\n\n");

    for f in files {
        if let Some(origin) = &f.origin {
            content.push_str(&format!("// --- {} ---\n\n", origin));
        }
        content.push_str(&f.code);
        content.push('\n');
    }

    let path = output_dir.join("models.rs");
    std::fs::write(&path, &content)?;
    eprintln!("Wrote {}", path.display());

    Ok(())
}

fn write_multi_files(files: &[GeneratedFile], output_dir: &Path) -> Result<()> {
    let mut mod_entries = Vec::new();

    for f in files {
        let content = build_file_content(f);
        let path = output_dir.join(&f.filename);
        std::fs::write(&path, &content)?;
        eprintln!("Wrote {}", path.display());

        let mod_name = f.filename.strip_suffix(".rs").unwrap_or(&f.filename);
        mod_entries.push(mod_name.to_string());
    }

    // Generate mod.rs
    let mut mod_content = String::from(HEADER);
    mod_content.push_str("\n\n");
    for m in &mod_entries {
        mod_content.push_str(&format!("pub mod {};\n", m));
    }

    let mod_path = output_dir.join("mod.rs");
    std::fs::write(&mod_path, &mod_content)?;
    eprintln!("Wrote {}", mod_path.display());

    Ok(())
}
